#!/bin/sh
cd "$(dirname "$0")" || exit

u="Usage: ./md2deck.sh DIR SLIDE [WIDTH] [HEIGHT] [TEMPLATE]"
if [ $# == 0 ]; then echo "${u}"; exit 0; fi

d=$1 # DIR
f=$2 # SLIDE
w=$3 # [WIDTH]
h=$4 # [HEIGHT]
t=$5 # [TEMPLATE]

ps="${f}" # path_src
pd="dist/" # path_dist
rw=${w:-1920} # decktape-width
rh=${h:-1080} # decktape-height
ut="" # user template
if [ $# == 5 ]; then ut="--data-dir=$(pwd) --template=../${t}"; fi

# start
cd "${d}" || exit

# generate html
pandoc -t revealjs -s -o "${ps}.html" "${ps}.md" ${ut} -V revealjs-url="../reveal.js"
open -a "Chromium" "${ps}.html"

# generate pdf
mkdir -p ${pd} # mkdir pd if pd does not exist
npx decktape "${ps}.html" "${pd}/${ps}.pdf" --size "${rw}"x"${rh}"

# end
cd "$(dirname "$0")" || exit
