#!/bin/sh
cd "$(dirname "$0")" || exit

u="Usage: ./md2deck DIR SLIDE [TEMPLATE]"
if [ $# == 0 ]; then echo "${u}"; exit 0; fi

d=$1 # DIR
f=$2 # SLIDE
t=$3 # [TEMPLATE]

ps="${f}" # path_src
pd="dist/" # path_dist
rw=1920 # decktape-width
rh=1080 # decktape-height
ut="" # user template
if [ $# == 3 ]; then ut="--data-dir=$(pwd) --template=../${t}"; fi

# start
cd "${d}" || exit

# generate html
pandoc -t revealjs -s -o "${ps}.html" "${ps}.md" ${ut} -V revealjs-url="../reveal.js"
open -a "Chromium" "${ps}.html"

# generate pdf
mkdir -p ${pd} # mkdir pd if pd does not exist
npx decktape "${ps}.html" "${pd}/${ps}.pdf" --size "${rw}"x"${rh}"

# end
cd "$(dirname "$0")" || exit
